---
- name: Create shared srv folder
  file:
    path: "{{ vhost_base_path }}/shared"
    state: directory

- name: Create blocking robots.txt
  copy:
    src: robots.txt
    dest: "{{ vhost_base_path }}/shared/robots.txt"

- name: Create DocumentRoot folders
  file:
          path: "{{ vhost_base_path }}/{{ item['host'] }}"
          state: directory
          owner: www-data
          group: www-data
  with_items: vhost_sites

- name: Create apache2 vhosts
  template:
    src: apache2/vhost.conf.j2
    dest: /etc/apache2/sites-available/{{ item['host'] }}.conf
  with_items: vhost_sites

- name: Enable apache2 vhosts
  file:
    src: /etc/apache2/sites-available/{{ item['host'] }}.conf
    dest: /etc/apache2/sites-enabled/{{ item['host'] }}.conf
    state: link
  with_items: vhost_sites
  notify: Restart apache
  when: "item['disabled']|default(false) != True"
